# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        gestionCandidat:
            entity:
                class: UserBundle:Candidat
                property: email
         
        gestionRecruteur:
            entity:
                class: UserBundle:Recruteur
                property: email
                
        checkCandidatRecruteur:
            chain:
                providers: [ gestionCandidat, gestionRecruteur ]

        
        
        in_memory:
            memory: ~
    
    encoders:
        UserBundle\Entity\Candidat: plaintext
        UserBundle\Entity\Recruteur: plaintext

    
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: checkCandidatRecruteur
            
            form_login:
                login_path: login
                check_path: loginCheck
                default_target_path: /
            
            logout:
                path: logOut
                target: /                
                
    access_control:
        - { path: ^/recruteur/profil, roles: ROLE_RECRUTEUR }
        
        - { path: ^/offre/nouveau , roles: ROLE_RECRUTEUR }
        - { path: ^/offre/modifier, roles: ROLE_RECRUTEUR }
        - { path: ^/candidat/modifier, roles: ROLE_CANDIDAT}
        
        
                
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
